In [2]:
import numpy as np

In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
np.__version__

'1.24.3'

In [5]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [6]:
type(array1)

numpy.ndarray

In [7]:
array2=np.array([[1,2],[3,4]])
array2

array([[1, 2],
       [3, 4]])

In [8]:
arr2=np.array([
                [1,2,3.3],
                [4,5,6.4]
])
arr2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [10]:
arr3=np.array([
               [
                   [1,2,3],
                   [4,5,6],
                   [7,8,9]
               ],
               [
                   [10,11,12],
                   [13,14,15],
                   [16,17,18]
               ]
    
])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
arr=np.array([
              [
                  [1,2],
                  [3,4]
              ],
              [
                  [5,6],
                  [7,8]
              ]
])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
arr5=np.array((12,13,14))
arr5

array([12, 13, 14])

In [12]:
arr3.ndim

3

In [14]:
arr6=np.array([1,2,3,4],ndmin=4)
arr6

array([[[[1, 2, 3, 4]]]])

In [15]:
arr6.shape

(1, 1, 1, 4)

In [16]:
arr3.shape

(2, 3, 3)

## 

In [17]:
arr2[0][1]

2.0

In [19]:
arr[1][1]

array([7, 8])

In [27]:
for x in range(0,2):
    for y in range(0,3):
        print(arr2[x][y])

1.0
2.0
3.3
4.0
5.0
6.4


In [32]:
arr2.dtype

dtype('float64')

In [34]:
array5=np.array([1,2,3,4,5],dtype='S')
array5

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [35]:
array5conv=array5.astype('i')
array5conv

array([1, 2, 3, 4, 5], dtype=int32)

In [36]:
array5float=array5conv.astype('f')
array5float

array([1., 2., 3., 4., 5.], dtype=float32)

In [40]:
numone=np.ones((5,5),dtype=int)
numone

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
numon=np.ones((1,3,3))
numon

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [44]:
numzero=np.zeros((3,2),dtype=int)
numzero

array([[0, 0],
       [0, 0],
       [0, 0]])

In [45]:
rang_arr=np.arange(0,10,3)
rang_arr

array([0, 3, 6, 9])

In [46]:
a=np.random.randint(low=2,size=5)
a

array([1, 1, 0, 0, 1])

In [47]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[1, 5, 1],
       [1, 4, 5]])

In [48]:
np.concatenate([array1,arr5])

array([ 1,  2,  3, 12, 13, 14])

In [49]:
flatarr=arr3.flatten()
flatarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [53]:
np.reshape(flatarr[:9],(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [59]:
import pandas as pd
df=pd.DataFrame(arr2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.4